on:
  push:
    branches:
      - main
      - "test/**" # Push events to branches matching refs/heads/test/[ANYTHING]
      - "test-*" # Push events to branches matching refs/heads/test-[ANYTHING]
  pull_request:

name: beta toolchain unit tests

jobs:
  unit-stable:
    name: beta toolchain unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
