on:
  push:
    branches:
      - main
      - "test/**" # Push events to branches matching refs/heads/test/[ANYTHING]
      - "test-*" # Push events to branches matching refs/heads/test-[ANYTHING]
  pull_request:

name: rustfmt check

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
