on:
  push:
    branches:
      - main
      - "test/**" # Push events to branches matching refs/heads/test/[ANYTHING]
      - "test-*" # Push events to branches matching refs/heads/test-[ANYTHING]
  pull_request:

name: clippy lints

jobs:
  clippy-stable:
    name: stable toolchain lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  clippy-beta:
    name: beta toolchain lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
