on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
      - "test/**" # Push events to branches matching refs/heads/test/[ANYTHING]
      - "test-*" # Push events to branches matching refs/heads/test-[ANYTHING]
  pull_request:

name: unit tests (stable toolchain)

jobs:
  unit-stable:
    name: default
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib

  unit-stable-all-features:
    name: all features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --lib
